# Generated by Django 3.2.15 on 2022-10-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20221019_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Caption'),
        ),
    ]
