# Generated by Django 4.0.8 on 2023-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_storystream_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storystream',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
