# Generated by Django 3.2.15 on 2022-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='text_preview',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
